name: CI
on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: MunifTanjim/setup-neovim-action@v1
      - name: Install plenary
        run: |
          git clone --depth 1 https://github.com/idanarye/plenary.nvim --branch async-testing ../plenary.nvim
      - name: Run tests
        run: |
          make test
