on:
  push:
    branches:
      - develop
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: main
      - name: Update main branch to develop branch
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git fetch origin develop
          git merge --ff-only origin/develop
          git push
permissions:
  contents: write
  pull-requests: write
  issues: write
